title: AlienSearch
author: Naresh Rawat
email: hoagss@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Welcome to Aliensearch

# social links
twitter_username: natsu
github_username:  hoagss

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
